# Load every node and link

In [1]:
import shapefile
import pandas as pd
from pyproj import Transformer

In [2]:
node_path = '../data/raw_data/node_link/MOCT_NODE.shp'
link_path = '../data/raw_data/node_link/MOCT_LINK.shp'

node_shp = shapefile.Reader(node_path, encoding='cp949')
link_shp = shapefile.Reader(link_path, encoding='cp949')

In [3]:
node_col = [x[0] for x in node_shp.fields][1:]
node_data = node_shp.records()
node_coord = [s.points[0] for s in node_shp.shapes()]

node_df = pd.DataFrame(node_data, columns=node_col)
node_df = node_df.assign(coords=node_coord)


link_col = [x[0] for x in link_shp.fields][1:]
link_data = link_shp.records()

link_df = pd.DataFrame(link_data, columns=link_col)

In [4]:
link_df

,LINK_ID,F_NODE,T_NODE,LANES,ROAD_RANK,ROAD_TYPE,ROAD_NO,ROAD_NAME,ROAD_USE,MULTI_LINK,...,MAX_SPD,REST_VEH,REST_W,REST_H,C-ITS,LENGTH,UPDATEDATE,REMARK,HIST_TYPE,HISTREMARK
0,2660315900,2660132500,2660132800,1,107,000,-,삼포해변길,0,0,...,30,0,0,0,0,715.687424,20230519,,,
1,2660336100,2660139100,2660139200,1,107,000,-,화암사길,0,0,...,50,0,0,0,0,942.762880,20230519,,,
2,3260017204,3260008202,3260008203,2,103,000,2,남승룡로,0,0,...,60,0,0,0,0,76.039806,20230519,,,
3,3240003900,3240002000,3240002100,3,107,000,-,영산로,0,0,...,60,0,0,0,0,120.458001,20230519,,,
4,3260023002,3260082400,3260089600,3,103,000,17,백강로,0,0,...,50,0,0,0,0,87.589918,20230519,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545707,1610126800,1610048100,1610046800,4,104,000,-,영종대로,0,0,...,50,0,0,0,0,706.106333,20230519,,,
545708,3190270000,3190005100,3190082600,1,107,000,-,종산로,0,0,...,50,0,0,0,0,323.012917,20230519,,,
545709,3960233200,3960089500,3960012801,1,107,000,-,두항길,0,0,...,50,0,0,0,0,1215.130137,20230519,,,
545710,2140742600,2140292900,2140003300,1,107,000,-,승학동길,0,0,...,50,0,0,0,0,69.740102,20230519,,,
545711,2140751400,2140303100,2140052001,1,107,000,-,-,0,0,...,50,0,0,0,0,120.092953,20230519,도로명없음,,

# Get daegu node and link

In [5]:
daegu_id_set = set([str(i) for i in range(150, 158)])

nodes = node_df[node_df['NODE_ID'].map(lambda x:x[0:3] in daegu_id_set)].reset_index(drop=True)
links = link_df[link_df['LINK_ID'].map(lambda x:x[0:3] in daegu_id_set)].reset_index(drop=True)

In [6]:
transformer = Transformer.from_crs('EPSG:5186', 'EPSG:4326')
nodes[['latitude', 'longitude']] = [[*transformer.transform(x, y)] for y, x in nodes['coords']]
del nodes['coords']

In [7]:
nodes

,NODE_ID,NODE_TYPE,NODE_NAME,TURN_P,UPDATEDATE,REMARK,HIST_TYPE,HISTREMARK,latitude,longitude
0,1520001500,101,달서교,0,20231013,,NODE0005,,35.880758,128.534027
1,1500004400,101,종각네거리,1,20230519,,,,35.869226,128.604073
2,1500004800,101,제일교회,0,20230519,,,,35.870140,128.606408
3,1510005800,101,원불교동호출장소,1,20230519,,,,35.866038,128.724867
4,1510005801,101,신서동540,0,20230519,,,,35.866360,128.725853
...,...,...,...,...,...,...,...,...,...,...
5572,1500000900,104,대봉교,0,20230519,,,,35.854962,128.607463
5573,1570224901,101,금포리1157,1,20230519,,,,35.777996,128.428355
5574,1540125000,101,구암동719,0,20230519,,,,35.927802,128.554163
5575,1570235400,101,중리507-1,0,20230519,,,,35.689787,128.454712
5576,1500007801,101,남산동303,0,20230519,,,,35.866236,128.589173

In [8]:
links

,LINK_ID,F_NODE,T_NODE,LANES,ROAD_RANK,ROAD_TYPE,ROAD_NO,ROAD_NAME,ROAD_USE,MULTI_LINK,...,MAX_SPD,REST_VEH,REST_W,REST_H,C-ITS,LENGTH,UPDATEDATE,REMARK,HIST_TYPE,HISTREMARK
0,1570824300,1570275000,1570274900,1,104,000,-,비슬로134길,0,0,...,30,0,0,0,0,102.653427,20230519,,,
1,1570719900,1570249700,1570200601,2,104,000,-,다사로,0,0,...,40,0,0,0,0,96.880033,20230519,,,
2,1570727900,1570238500,1570237800,1,104,000,-,대실역남로2길,0,0,...,50,0,0,0,0,30.505272,20230519,,,
3,1550385200,1550108800,1550108900,1,104,000,-,동대구로,0,0,...,40,0,0,0,0,82.305316,20230519,,,
4,1540308700,1540028101,1540118100,1,104,000,-,동천로23길,0,0,...,60,0,0,0,0,67.867096,20230519,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15983,1540423900,1540002101,1540103600,1,104,000,-,매천로8길,0,0,...,50,0,0,0,0,417.149746,20230519,,,
15984,1550002801,1550001600,1550001501,5,103,000,25,달구벌대로,0,0,...,70,0,0,0,0,70.569908,20230519,,,
15985,1550012502,1550005401,1550006400,2,104,000,-,용학로,0,0,...,40,0,0,0,0,174.531514,20230519,,,
15986,1510525100,1510171700,1510003302,1,104,000,-,아양로41길,0,0,...,10,0,0,0,0,266.435519,20230519,,,
15987,1570746700,1570255400,1570255300,1,104,000,-,세천로7길,0,0,...,60,0,0,0,0,27.151425,20230519,,,

# Save

In [9]:
nodes.sort_values(by=['NODE_ID']).to_csv('../data/processed_data/node_link/daegu_nodes.csv', index=False)
links.sort_values(by=['LINK_ID']).to_csv('../data/processed_data/node_link/daegu_links.csv', index=False)